version: 2

models:
  - name: bronze_flights
    description: "Bronze layer of flights data"
    columns:
      - name: id
        description: "Unique flight ID"
        tests:
          - not_null
          - unique
      - name: flight_number
        description: "Flight number"
        tests:
          - not_null
      - name: origin
        description: "Origin airport code"
        tests:
          - not_null
      - name: destination
        description: "Destination airport code"
        tests:
          - not_null

