version: 2

sources:
  - name: raw
    database: flight_db
    schema: raw
    tables:
      - name: bronze_airlines
      - name: bronze_airports
      - name: bronze_flights
      - name: airports
      - name: weather

